# Generated by Django 3.2.4 on 2021-06-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('link', models.CharField(blank=True, max_length=400, null=True, verbose_name='Link to project')),
                ('deployed_link', models.CharField(blank=True, max_length=400, null=True, verbose_name='Link to deployed project')),
                ('description', models.TextField(verbose_name='Description')),
                ('started_on', models.DateField(verbose_name='Starting date')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.project')),
            ],
        ),
    ]
