# Generated by Django 3.2.4 on 2021-06-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='public',
            field=models.BooleanField(default=None, verbose_name='Public or not'),
            preserve_default=False,
        ),
    ]
