# Generated by Django 3.2.4 on 2021-06-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_project_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='public',
            field=models.BooleanField(verbose_name='Public'),
        ),
    ]
